name: "CI" 

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]
  schedule:
    - cron: '16 14 * * 3'

jobs:
  analyze:
    name: Analyze
    runs-on: windows-latest
    permissions:
      actions: read
      contents: read
      security-events: write 
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
        dotnet: ['7.0']

    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        config-file: ./.github/codeql-config.yml


    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore ./src
    - name: Test
      run: dotnet test --no-build --no-restore --verbosity normal
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2