name: publish-nuget

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix: 
        dotnet: ['7.0']
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}
        include-prerelease: True

    - name: Create NuGet Package
      run: dotnet pack -c Release 
                    /p:ContinuousIntegrationBuild=true 
                    /p:Version=${{ github.event.release.tag_name }} 
                    /p:PackageReleaseNotes="See https://github.com/chrisfactory/Net.Core.Communication/releases/tag/${{ github.event.release.tag_name }}"
      working-directory: .

    - name: Archive Net.Core.Communication.Core NuGet Package
      uses: actions/upload-artifact@v1
      with:
        name: Net.Core.Communication.Core
        path: ./src/Core/bin/Release/Net.Core.Communication.Core.${{ github.event.release.tag_name }}.symbols.nupkg

    - name: Archive Net.Core.Communication.Injection.Client NuGet Package
      uses: actions/upload-artifact@v1
      with:
        name: Net.Core.Communication.Injection.Client
        path: ./src/Providers/Injection/Communication.Injection.Client/bin/Release/Net.Core.Communication.Injection.Client.${{ github.event.release.tag_name }}.symbols.nupkg

    - name: Archive Net.Core.Communication.DynamicApi.Core NuGet Package
      uses: actions/upload-artifact@v1
      with:
        name: Net.Core.Communication.DynamicApi.Core
        path: ./src/Providers/DynamicApi/Communication.DynamicApi.Core/bin/Release/Net.Core.Communication.DynamicApi.Core.${{ github.event.release.tag_name }}.symbols.nupkg       

    - name: Archive Net.Core.Communication.DynamicApi.Client NuGet Package
      uses: actions/upload-artifact@v1
      with:
        name: Net.Core.Communication.DynamicApi.Client
        path: ./src/Providers/DynamicApi/Communication.DynamicApi.Client/bin/Release/Net.Core.Communication.DynamicApi.Client.${{ github.event.release.tag_name }}.symbols.nupkg   
   
    - name: Archive Net.Core.Communication.DynamicApi.Hosting NuGet Package
      uses: actions/upload-artifact@v1
      with:
        name: Net.Core.Communication.DynamicApi.Hosting
        path: ./src/Providers/DynamicApi/Communication.DynamicApi.Hosting/bin/Release/Net.Core.Communication.DynamicApi.Hosting.${{ github.event.release.tag_name }}.symbols.nupkg   



    - name: Publish Nuget Package
      run: dotnet nuget push **/*.symbols.nupkg --api-key ${{ secrets.NET_CORE_COMMUNICATION_NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json 

      